FROM node:22-alpine
WORKDIR /srv

COPY package*.json ./
COPY apps/backend/package*.json ./apps/backend/
COPY apps/frontend/package*.json ./apps/frontend/
COPY packages/shared/package*.json ./packages/shared/
RUN npm install

COPY apps/backend/tsconfig*.json ./apps/backend/
COPY apps/backend/nest-cli.json ./apps/backend/
COPY apps/backend/src ./apps/backend/src
COPY apps/backend/test ./apps/backend/test
COPY packages/shared ./packages/shared

RUN npm run build:shared

WORKDIR /srv/apps/backend

EXPOSE 3000
CMD ["npm", "run", "start:dev"]