FROM node:22-alpine
WORKDIR /srv/backend

COPY package*.json ./
RUN npm install

COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY src ./src
COPY test ./test

EXPOSE 3000
CMD ["npm", "run", "start:dev"]