import { applyDecorators } from "@nestjs/common";
import { ApiProperty } from "@nestjs/swagger";

export const UserEntityDoc = {
  Id: () => applyDecorators(
    ApiProperty({
      title: 'User ID',
      description: 'The unique identifier for the user, generated by the system.',
      type: String,
      format: 'uuid',
      example: 'a3f1c2d4-b5e7-4f9c-8d3a-1e2f3b4c5d6e',
      readOnly: true,
    })
  ),

  Username: () => applyDecorators(
    ApiProperty({
      // Basic info
      title: 'Username',
      description: 'The unique username of the user. Must be alphanumeric.',

      // Type hints (useful for complex types, normally inferred automatically)
      type: String,
      format: 'string', // OpenAPI formats: 'email', 'uuid', 'date', 'date-time', 'password', 'binary', 'byte', 'uri'

      // Validation hints (purely visual in Swagger, does NOT enforce validation — use class-validator for that)
      minLength: 3,
      maxLength: 20,
      pattern: '^[a-zA-Z0-9]+$',

      // Example values
      example: 'johndoe',          // single example
      examples: {                   // multiple examples (overrides example if both set)
        simple: {
          summary: 'Simple username',
          value: 'johndoe',
        },
        withNumbers: {
          summary: 'Username with numbers',
          value: 'johndoe42',
        },
      },

      // Availability
      required: true,               // marks field as required in Swagger UI (default: true)
      nullable: false,              // whether the field can be null
      uniqueItems: true,            // hints this should be unique (informational only)

      // Read/write control
      readOnly: false,              // if true, only shown in responses, not in request body
      writeOnly: false,             // if true, only shown in request body, not in responses (useful for passwords)
      deprecated: false,            // marks the field as deprecated in Swagger UI

      // Default value (shown in Swagger UI as prefilled)
      default: undefined,
    })
  ),

  Password: () => applyDecorators(
    ApiProperty({
      title: 'Password',
      description: 'The account password. Never returned in responses. Encrypted and stored securely on the server.',
      type: String,
      format: 'password',
      example: 'Str0ng!Pass',
      minLength: 8,
      maxLength: 64,
      writeOnly: true,
      required: true,
    })
  ),

  Email: () => applyDecorators(
    ApiProperty({
      title: 'Email address',
      description: 'The email address of the user. Must be unique.',
      type: String,
      format: 'email',
      example: 'john@example.com',
      required: true,
      nullable: false,
      uniqueItems: true,            // hints this should be unique (informational only)
    })
  ),

  PhoneWzc: () => applyDecorators(
    ApiProperty({
      title: 'Phone country code',
      description: 'The country code for the phone number (1-3 digits). Example: 33 for France, 1 for USA.',
      type: String,
      pattern: '^\\d{1,3}$',
      example: '33',
      required: false,
      nullable: true,
    })
  ),

  PhoneNumber: () => applyDecorators(
    ApiProperty({
      title: 'Phone number',
      description: 'The phone number without country code (7-15 digits). Must be provided with phoneWzc.',
      type: String,
      pattern: '^\\d{7,15}$',
      example: '612345678',
      required: false,
      nullable: true,
    })
  ),

  Bio: () => applyDecorators(
    ApiProperty({
      title: 'Bio',
      description: 'A short biography or personal description.',
      type: String,
      example: 'I love gaming and collecting rare titles!',
      required: false,
      nullable: true,
    })
  ),

  Avatar: () => applyDecorators(
    ApiProperty({
      title: 'Avatar',
      description: 'The name of the avatar image file.',
      type: String,
      maxLength: 255,
      example: 'avatar-12345.jpg',
      required: false,
      nullable: true,
    })
  ),

  Wallet: () => applyDecorators(
    ApiProperty({
      title: 'Wallet balance',
      description: 'The current balance in the user\'s wallet. Cannot be negative.',
      type: Number,
      format: 'decimal',
      minimum: 0,
      example: 49.99,
      required: false,
      default: 0,
    })
  ),

  CreationDate: () => applyDecorators(
    ApiProperty({
      title: 'Creation date',
      description: 'The date the account was created, automatically set by the server.',
      type: String,
      format: 'date',
      example: '2024-01-15',
      readOnly: true,
    })
  ),

  FirstName: () => applyDecorators(
    ApiProperty({
      title: 'First name',
      description: 'The first name of the user.',
      type: String,
      maxLength: 100,
      example: 'John',
      required: false,
      nullable: true,
    })
  ),

  LastName: () => applyDecorators(
    ApiProperty({
      title: 'Last name',
      description: 'The last name of the user.',
      type: String,
      maxLength: 100,
      example: 'Doe',
      required: false,
      nullable: true,
    })
  ),

  Country: () => applyDecorators(
    ApiProperty({
      title: 'Country',
      description: 'The country where the user is located.',
      type: String,
      maxLength: 100,
      example: 'France',
      required: false,
      nullable: true,
    })
  ),

  BillingAddress: () => applyDecorators(
    ApiProperty({
      title: 'Billing address',
      description: 'The full billing address for purchases and transactions.',
      type: String,
      example: '123 Main Street, Paris, 75001, France',
      required: false,
      nullable: true,
    })
  ),

  NewsletterSubscribed: () => applyDecorators(
    ApiProperty({
      title: 'Newsletter subscription',
      description: 'Whether the user is subscribed to the newsletter.',
      type: Boolean,
      example: true,
      required: false,
      default: false,
    })
  ),

  BirthdayDate: () => applyDecorators(
    ApiProperty({
      title: 'Birthday',
      description: "The user's date of birth in YYYY-MM-DD format. Must be in the past.",
      type: String,
      format: 'date',
      example: '1990-05-15',
      required: false,
      nullable: true,
    })
  ),

  CartId: () => applyDecorators(
    ApiProperty({
      title: 'Cart ID',
      description: 'UUID of the shopping cart associated with this user. Null if no cart has been created yet.',
      type: String,
      format: 'uuid',
      example: 'b7e2a1d3-c4f6-4e8b-9a0d-2f3e4c5b6a7d',
      required: false,
      nullable: true,
      readOnly: true,
    })
  ),
}