import { applyDecorators } from "@nestjs/common";
import { ApiProperty } from "@nestjs/swagger";

export class MakeDoc {
  static MakeUUID(title: string) {
    return () => applyDecorators(
      ApiProperty({
        title,
        description: 'Unique identifier, generated by the system.',
        type: String,
        format: 'uuid',
        example: '08dbd076-c3d8-46d4-bb0d-ebedc8bebd1f',
        readOnly: true,
      }),
    )
  }

  static makeSerial(title: string) {
    return applyDecorators(
      ApiProperty({
        title,
        description: 'Unique identifier, auto-incremented by the system.',
        type: Number,
        example: 42,
        readOnly: true,
      }),
    )
  }
}