import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import { TicketStatus } from 'src/tickets/entities/ticket.entity';

export const TicketEntityDoc = {
  Id: () =>
    applyDecorators(
      ApiProperty({
        title: 'Ticket ID',
        description: 'Unique identifier, generated by the system.',
        type: String,
        format: 'uuid',
        example: 'f3a1c2d4-b5e7-4f9c-8d3a-1e2f3b4c5d6e',
        readOnly: true,
      }),
    ),

  Email: (required = true) =>
    applyDecorators(
      ApiProperty({
        title: 'Contact email',
        description:
          'Email address to use for replies. Does not have to match the account email.',
        type: String,
        format: 'email',
        maxLength: 255,
        example: 'john@example.com',
        required: required,
      }),
    ),

  Reason: (required = true) =>
    applyDecorators(
      ApiProperty({
        title: 'Reason',
        description:
          'Short subject line summarising the issue. Cannot be blank.',
        type: String,
        minLength: 1,
        maxLength: 255,
        example: 'Cannot access my purchased game',
        required: required,
      }),
    ),

  Content: (required = true) =>
    applyDecorators(
      ApiProperty({
        title: 'Content',
        description: 'Full description of the issue. Cannot be blank.',
        type: String,
        minLength: 1,
        example:
          'After purchasing Black Ops I cannot find the product key in my library.',
        required: required,
      }),
    ),

  Status: (required = true) =>
    applyDecorators(
      ApiProperty({
        title: 'Status',
        description:
          'Current state of the ticket. Only employees can change this.',
        enum: TicketStatus,
        enumName: 'TicketStatus',
        example: TicketStatus.OPEN,
        default: TicketStatus.OPEN,
        required: required,
      }),
    ),

  CreatedAt: () =>
    applyDecorators(
      ApiProperty({
        title: 'Created at',
        description:
          'Timestamp of ticket submission. Set automatically by the server.',
        type: String,
        format: 'date-time',
        example: '2024-01-15T10:23:00Z',
        readOnly: true,
      }),
    ),

  UserId: () =>
    applyDecorators(
      ApiProperty({
        title: 'User ID',
        description:
          'UUID of the user who submitted the ticket. Null for guest submissions.',
        type: String,
        format: 'uuid',
        example: 'a3f1c2d4-b5e7-4f9c-8d3a-1e2f3b4c5d6e',
        nullable: true,
        required: false,
        readOnly: true,
      }),
    ),
};
