import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';

export const UserEntityDoc = {
  // -------------------------------------------------------
  // User (core)
  // -------------------------------------------------------

  Id: () =>
    applyDecorators(
      ApiProperty({
        title: 'User ID',
        description: 'Unique identifier, generated by the system.',
        type: String,
        format: 'uuid',
        example: '08dbd076-c3d8-46d4-bb0d-ebedc8bebd1f',
        readOnly: true,
      }),
    ),

  Username: (required = true) =>
    applyDecorators(
      ApiProperty({
        title: 'Username',
        description: 'Unique display name. Alphanumeric, 3-50 characters.',
        type: String,
        minLength: 3,
        maxLength: 50,
        pattern: '^[a-zA-Z0-9_]+$',
        example: 'johndoe',
        required: required,
        nullable: false,
      }),
    ),

  Password: (required = true) =>
    applyDecorators(
      ApiProperty({
        title: 'Password',
        description:
          'Account password. Never returned in responses. Hashed server-side.',
        type: String,
        format: 'password',
        minLength: 8,
        maxLength: 128,
        example: 'Str0ng!Pass',
        writeOnly: true,
        required: required,
      }),
    ),

  Email: (required = true) =>
    applyDecorators(
      ApiProperty({
        title: 'Email address',
        description:
          'Must be unique. Partially masked in responses for privacy.',
        type: String,
        format: 'email',
        example: 'john@example.com',
        required: required,
        nullable: false,
      }),
    ),

  PhoneNumber: () =>
    applyDecorators(
      ApiProperty({
        title: 'Phone number',
        description:
          'Must be unique in combination with country code. E.164 format recommended.',
        type: String,
        pattern: '^\\+?[1-9]\\d{1,14}$',
        example: '+33612345678',
        required: false,
        nullable: true,
      }),
    ),

  Bio: () =>
    applyDecorators(
      ApiProperty({
        title: 'Bio',
        description: 'Short public biography. Max 500 characters.',
        type: String,
        maxLength: 500,
        example: 'I love gaming and collecting rare titles!',
        required: false,
        nullable: true,
      }),
    ),

  Avatar: () =>
    applyDecorators(
      ApiProperty({
        title: 'Avatar filename',
        description:
          'Filename of the stored avatar image. Use PATCH /user/avatar to change.',
        type: String,
        maxLength: 255,
        example: 'avatar-3f2a1c.jpg',
        required: false,
        nullable: true,
        readOnly: true,
      }),
    ),

  CreatedAt: () =>
    applyDecorators(
      ApiProperty({
        title: 'Account creation date',
        description: 'Set automatically by the server on registration.',
        type: String,
        format: 'date-time',
        example: '2024-01-15T10:23:00Z',
        readOnly: true,
      }),
    ),

  // -------------------------------------------------------
  // UserProfile
  // -------------------------------------------------------

  FirstName: (nullable = false) =>
    applyDecorators(
      ApiProperty({
        title: 'First name',
        type: String,
        maxLength: 100,
        example: 'John',
        required: false,
        nullable: nullable,
      }),
    ),

  LastName: (nullable = false) =>
    applyDecorators(
      ApiProperty({
        title: 'Last name',
        type: String,
        maxLength: 100,
        example: 'Doe',
        required: false,
        nullable: nullable,
      }),
    ),

  Birthdate: () =>
    applyDecorators(
      ApiProperty({
        title: 'Date of birth',
        description:
          'ISO 8601 date. Must be in the past and at least 13 years ago.',
        type: String,
        format: 'date',
        example: '1990-05-15',
        required: false,
        nullable: true,
      }),
    ),

  Country: (nullable = false) =>
    applyDecorators(
      ApiProperty({
        title: 'Country',
        description: 'ISO 3166-1 alpha-2 country code.',
        type: String,
        minLength: 2,
        maxLength: 2,
        pattern: '^[A-Z]{2}$',
        example: 'FR',
        required: false,
        nullable: nullable,
      }),
    ),

  Newsletter: () =>
    applyDecorators(
      ApiProperty({
        title: 'Newsletter opt-in',
        description: 'Whether the user has opted into the newsletter.',
        type: Boolean,
        example: false,
        required: false,
        default: false,
      }),
    ),

  // -------------------------------------------------------
  // UserBilling
  // -------------------------------------------------------

  City: () =>
    applyDecorators(
      ApiProperty({
        title: 'City',
        type: String,
        maxLength: 100,
        example: 'Paris',
        required: false,
        nullable: false,
      }),
    ),

  PostalCode: () =>
    applyDecorators(
      ApiProperty({
        title: 'Postal code',
        type: String,
        maxLength: 20,
        example: '75001',
        required: false,
        nullable: false,
      }),
    ),

  AddressLine1: () =>
    applyDecorators(
      ApiProperty({
        title: 'Address line 1',
        description: 'Street address, P.O. box, etc.',
        type: String,
        maxLength: 255,
        example: '12 Rue de Rivoli',
        required: false,
        nullable: false,
      }),
    ),

  AddressLine2: () =>
    applyDecorators(
      ApiProperty({
        title: 'Address line 2',
        description: 'Apartment, suite, unit, building, floor, etc.',
        type: String,
        maxLength: 255,
        example: 'Apt 4B',
        required: false,
        nullable: true,
      }),
    ),
};
