import { ApiProperty } from "@nestjs/swagger";
import { ExactData, ReviewVote } from "@unlockit/shared";

export class ReviewVoteDto implements ReviewVote {
  @ApiProperty({
    title: 'Review ID',
    description: 'Unique identifier, generated by the system.',
    type: String,
    format: 'uuid',
    example: '08dbd076-c3d8-46d4-bb0d-ebedc8bebd1f',
    readOnly: true,
  })
  helpful: boolean | null;
}

const _assertExact: ExactData<ReviewVote, ReviewVoteDto> = true;